name: Update Citations

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

jobs:
  update-citations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install requests beautifulsoup4 pyyaml

      - name: Update Citations
        run: python scripts/update_citations.py

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add _data/citations.yml
          git commit -m "Update citation count"
          git push
